# Problem: https://leetcode.com/problems/subsets-ii/
# Idea: Similar like subsets. [1,2,2] gets generated by the first recursion.
# But the while loop before second recursion makes sure [1,2,2] doesn't get generated again.
# Time: O(2^n)
# Space: O(n)

def subsets_with_dup(nums):
    nums.sort()
    result = []
    backtrack(nums, 0, [], result)
    return result


def backtrack(nums, ind, path, result):
    if ind == len(nums):
        result.append(path[:])
        return

    # pick
    path.append(nums[ind])
    backtrack(nums, ind + 1, path, result)
    path.pop()  # backtrack

    # skip duplicates before not-pick
    while ind + 1 < len(nums) and nums[ind] == nums[ind + 1]:
        ind += 1

    # not pick
    backtrack(nums, ind + 1, path, result)


# -------- Test --------
nums = [1, 2, 2]
print(subsets_with_dup(nums))
# Expected:
# [
#   [],
#   [2],
#   [2,2],
#   [1],
#   [1,2],
#   [1,2,2]
# ]
